### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [KrzysztofSobota/Finish-project#7]
Grade: **meets all requirements**I

I know you had some trouble setting it up, and mainly submitting it, but I believe you fixed a great deal about it. Right now I will say to focus in syntax and structure. By practicing, you acquire a level of proficiency that you may benefit from, not many people keep building healthy habits.

Congratulations of finishing the course!

Best of luck!

**Comment by KrzysztofSobota** [comment]
Thanks!!
